// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_no_brain = "CgkIgfrixdgKEAIQAw"; // <GPGSID>
        public const string achievement_what_a_shock = "CgkIgfrixdgKEAIQBQ"; // <GPGSID>
        public const string achievement_mad_scientist = "CgkIgfrixdgKEAIQAQ"; // <GPGSID>
        public const string achievement_shiny_shiny = "CgkIgfrixdgKEAIQBw"; // <GPGSID>
        public const string achievement_i_believe_i_can_fly = "CgkIgfrixdgKEAIQBA"; // <GPGSID>
        public const string achievement_by_all_means = "CgkIgfrixdgKEAIQBg"; // <GPGSID>
        public const string achievement_at_least_its_a_success = "CgkIgfrixdgKEAIQCA"; // <GPGSID>
        public const string achievement_big_brain = "CgkIgfrixdgKEAIQAg"; // <GPGSID>

}

